# Generated by Django 3.2.16 on 2024-03-27 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motobike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='Производитель')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
                ('foto', models.ImageField(blank=True, upload_to='moto_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorbike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motobikes.motobike')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
