# Generated by Django 3.2.16 on 2024-03-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motobikes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
