# Generated by Django 3.2.16 on 2024-03-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_motouser_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motouser',
            name='foto',
            field=models.ImageField(blank=True, upload_to='profile_images', verbose_name='Фото'),
        ),
    ]
