# Generated by Django 3.2.16 on 2024-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_motouser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='motouser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Обо мне'),
        ),
    ]
