# Generated by Django 3.2.16 on 2024-03-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(help_text="Нет нужного местоположения? Вы можете его\n        <a href='create_location/'>добавить</a>.<br>\n        Внимание! При покидании страницы данные формы не сохранятся.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='Местоположение'),
        ),
    ]
